name: design_system
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  
  ## UI
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

assets:
  images:
    - lib/assets/images/png/
    - lib/assets/images/svg/

  fonts:
    - family: HelveticaNeue
      fonts: 
        - assets: lib/assets/fonts/HelveticaNeueMedium.otf
          weight: 500
        - assets: lib/assets/fonts/HelveticaNeueRegular.otf
          weight: 400
    - family: BeTalentIcons
      fonts:
        - assets: lib/assets/fonts/BeTalentIcons.ttf

