// Mocks generated by Mockito 5.4.5 from annotations
// in be_talent/test/src/features/employees/view_model/employee_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:be_talent/src/core/core.dart' as _i6;
import 'package:be_talent/src/features/employees/data/repositories/remote_employee_repository.dart'
    as _i4;
import 'package:be_talent/src/features/employees/data/services/employee_service.dart'
    as _i2;
import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEmployeeService_0 extends _i1.SmartFake
    implements _i2.EmployeeService {
  _FakeEmployeeService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RemoteEmployeeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteEmployeeRepository extends _i1.Mock
    implements _i4.RemoteEmployeeRepository {
  @override
  _i2.EmployeeService get service =>
      (super.noSuchMethod(
            Invocation.getter(#service),
            returnValue: _FakeEmployeeService_0(
              this,
              Invocation.getter(#service),
            ),
            returnValueForMissingStub: _FakeEmployeeService_0(
              this,
              Invocation.getter(#service),
            ),
          )
          as _i2.EmployeeService);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i6.Employee>>> getEmployees() =>
      (super.noSuchMethod(
            Invocation.method(#getEmployees, []),
            returnValue:
                _i5.Future<_i3.Either<_i6.Failure, List<_i6.Employee>>>.value(
                  _FakeEither_1<_i6.Failure, List<_i6.Employee>>(
                    this,
                    Invocation.method(#getEmployees, []),
                  ),
                ),
            returnValueForMissingStub:
                _i5.Future<_i3.Either<_i6.Failure, List<_i6.Employee>>>.value(
                  _FakeEither_1<_i6.Failure, List<_i6.Employee>>(
                    this,
                    Invocation.method(#getEmployees, []),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, List<_i6.Employee>>>);
}
