name: be_talent
description: "Be Talent collaborators app"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

# Enable the following line to run the package in a monorepo.
# Waiting for resolve issue https://github.com/flutter/flutter/issues/160142
#resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  ## Design System
  design_system:
    path: ../../packages/design_system


dev_dependencies:
  flutter_test:
    sdk: flutter

  ## Utils
  flutter_native_splash: ^2.4.4

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/png/
