name: be_talent
description: "Be Talent collaborators app"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

# Enable the following line to run the package in a monorepo.
# Waiting for resolve issue https://github.com/flutter/flutter/issues/160142
#resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  ## Design System
  design_system:
    path: ../../packages/design_system

  ## Dependency Injection
  get_it: ^8.0.3

  ## Routing
  go_router: ^14.8.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  ## Utils
  flutter_native_splash: ^2.4.4
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/png/

  fonts:
    - family: Helvetica Neue
      fonts:
        - asset: packages/design_system/assets/fonts/HelveticaNeue-Regular.ttf
          weight: 400
        - asset: packages/design_system/assets/fonts/HelveticaNeue-Medium.ttf
          weight: 500

    - family: Inter
      fonts:
        - asset: packages/design_system/assets/fonts/Inter-VariableFont.ttf
          weight: 700
      
    - family: BeTalentIcons
      fonts:
        - asset: packages/design_system/assets/fonts/BeTalentIcons.ttf

