name: ds_example
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

# Enable the following line to run the package in a monorepo.
# Waiting for resolve issue https://github.com/flutter/flutter/issues/160142
#resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  design_system:
    path: ../../packages/design_system

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Helvetica Neue
      fonts:
        - asset: packages/design_system/assets/fonts/HelveticaNeue-Regular.ttf
          weight: 400

    - family: Helvetica Neue Medium
      fonts:
        - asset: packages/design_system/assets/fonts/HelveticaNeue-Medium.ttf
          weight: 500
          
    - family: Inter
      fonts:
        - asset: packages/design_system/assets/fonts/Inter-VariableFont.ttf
          weight: 700

    - family: BeTalentIcons
      fonts:
        - asset: packages/design_system/assets/fonts/BeTalentIcons.ttf