name: ds_example
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

# Enable the following line to run the package in a monorepo.
# Waiting for resolve issue https://github.com/flutter/flutter/issues/160142
#resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  design_system:
    path: ../../packages/design_system

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: HelveticaNeue
      fonts:
        - asset: packages/design_system/assets/fonts/HelveticaNeueMedium.otf
          weight: 500
        - asset: packages/design_system/assets/fonts/HelveticaNeueRegular.otf
          weight: 400
      
    - family: BeTalentIcons
      fonts:
        - asset: packages/design_system/assets/fonts/BeTalentIcons.ttf
  